name: build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghidra: "12.1.2"
            java: "21"
          - ghidra: "12.1"
            java: "21"
          - ghidra: "12.0.4"
            java: "21"
          - ghidra: "12.0.3"
            java: "21"
          - ghidra: "12.0.2"
            java: "21"
          - ghidra: "12.0.1"
            java: "21"
          - ghidra: "12.0"
            java: "21"
          - ghidra: "11.4.3"
            java: "21"
          - ghidra: "11.4.2"
            java: "21"
          - ghidra: "11.4.1"
            java: "21"
          - ghidra: "11.4"
            java: "21"
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0

      - name: Install Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@df83bc5529d1b5d2d06537b25a8e65b36b0fa92f # v2.0.4
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}

      - name: Build
        run: ./gradlew buildExtension

      - name: Check SLA timestamps
        run: ls -l $GHIDRA_INSTALL_DIR/Ghidra/Processors/x86/data/languages/*

      - name: Precompile slaspec
        run: $GHIDRA_INSTALL_DIR/support/sleigh $GHIDRA_INSTALL_DIR/Ghidra/Processors/x86/data/languages/x86-64.slaspec

      - name: Run tests
        run: xvfb-run ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-results-ghidra-${{ matrix.ghidra }}
          path: build/reports/tests/test/

      - name: Publish test report
        if: always()
        uses: dorny/test-reporter@d61b558e8df85cb60d09ca3e5b09653b4477cea7 # v1
        with:
          name: Tests (Ghidra ${{ matrix.ghidra }})
          path: build/test-results/test/*.xml
          reporter: java-junit
